INSERT INTO Residence_DB VALUES ('Alessandro','Agneti','alex.agneti@gmail.com','Non presente','Mobile','3928680992','DEP','101','Borgo 1',NULL);
INSERT INTO Residence_DB VALUES ('Giacomo','Buzzitta','giacomobuzzitta@libero.it','Non presente','Mobile','3312693245','DEP','103','Borgo 2',NULL);
INSERT INTO Residence_DB VALUES ('Andrea','Cau','cauandrea@hotmail.it','Non presente','Mobile','3468439253','DEP','105','Pigna 1',NULL);
INSERT INTO Residence_DB VALUES ('Flavio','Chioda','flaviochioda97@gmail.com','Non presente','Mobile','3407609567','LTM','110','Colonna 1',NULL);
INSERT INTO Residence_DB VALUES ('Gaetano','Ciccone','gaetano.ciccone97@gmail.com','Non presente','Mobile','3472430165','LTM','113','Pigna 1',NULL);
INSERT INTO Residence_DB VALUES ('Silvio Pablo','Cifone','SilvioCifone98@gmail.com','Non presente','Mobile','3427503332','DEP','106','Campo Marzio 2',NULL);
INSERT INTO Residence_DB VALUES ('Francesco','Cipolla','francescocpll@gmail.com','Non presente','Mobile','3272079936','LTM','114','Colonna 2',NULL);
INSERT INTO Residence_DB VALUES ('Alberto','Colopi','colopi.alberto@gmail.com','Non presente','Mobile','3899840644','DEP','111','Borgo 1',NULL);
INSERT INTO Residence_DB VALUES ('Gianfranco','Colucci','gianfrancolucci@gmail.com','Non presente','Mobile','3313062273','LTM','122','Borgo 1',NULL);
INSERT INTO Residence_DB VALUES ('Antonio','Cozzi','antoniocozzi2@gmail.com','Non presente','Mobile','3277935365','LTM','130','Colonna 2',NULL);
INSERT INTO Residence_DB VALUES ('Antonio','D''Ademo','antonio.dademo98@gmail.com','Non presente','Mobile','3467328232','DEP','112','Campo Marzio 1',NULL);
INSERT INTO Residence_DB VALUES ('Gabriele','De Trane','detranegabriele@gmail.com','Non presente','Mobile','3898869237','DEP','115','Ponte 1',NULL);
INSERT INTO Residence_DB VALUES ('Francesco','Del Prete','f.delprete06@gmail.com','Non presente','Mobile','3499591992','DEP','116','Ponte 2',NULL);
INSERT INTO Residence_DB VALUES ('Matteo','Di Masi','dimasimatteo@gmail.com','Non presente','Mobile','3348050905','DEP','117','Colonna 2',NULL);
INSERT INTO Residence_DB VALUES ('Alessio','Ferrigno','ferrignoalessio98@gmail.com','Non presente','Mobile','3929453613','DEP','121','Parione 2',NULL);
INSERT INTO Residence_DB VALUES ('Michele','Foderaro','michele.foderaro@virgilio.it','Non presente','Mobile','3662530814','LTM','131','Pigna 1',NULL);
INSERT INTO Residence_DB VALUES ('Antonino','Giacalone','antonino.giacalone9898@gmail.com','Non presente','Mobile','3891470615','DEP','123','Monti 1',NULL);
INSERT INTO Residence_DB VALUES ('Nicola','Iacovelli','nicolaiacovelli98@gmail.com','Non presente','Mobile','3279547326','DEP','124','Parione 2',NULL);
INSERT INTO Residence_DB VALUES ('Gaetano','La Porta','gaeta91@live.it','Non presente','Mobile','3888505774','DEP','125','Borgo 2',NULL);
INSERT INTO Residence_DB VALUES ('Leonardo','Lauriola','leonardo.lauriola19@gmail.com','Non presente','Mobile','3899533036','DEP','127','Pigna 2',NULL);
INSERT INTO Residence_DB VALUES ('Roberto','Lentini','roberto.lentini@live.com','Non presente','Mobile','3290461211','LTM','135','Parione 2',NULL);
INSERT INTO Residence_DB VALUES ('Antonino','Liberto','libertoantonio9804@gmail.com','Non presente','Mobile','3312218650','DEP','128','Pigna 1',NULL);
INSERT INTO Residence_DB VALUES ('Domenico','Licciardi','licciardi.domenico98@gmail.com','Non presente','Mobile','3488190480','LTM','136','Borgo 6',NULL);
INSERT INTO Residence_DB VALUES ('Alessandro','Littera','alessandro_998@live.it','Non presente','Mobile','3473276506','DEP','129','Colonna 1',NULL);
INSERT INTO Residence_DB VALUES ('Nicolò','Longobardo','longobardo23@gmail.com','Non presente','Mobile','3314682431','LTM','137','Borgo 2',NULL);
INSERT INTO Residence_DB VALUES ('Matteo Serafino','Manfreda','manfredamatteo44@gmail.com','Non presente','Mobile','3891508407','LTM','138','Monti 4',NULL);
INSERT INTO Residence_DB VALUES ('Luca','Mantione','luca.mantione@hotmail.it','Non presente','Mobile','3461013309','LTM','139','Parione 2',NULL);
INSERT INTO Residence_DB VALUES ('Francesco','Manuguerra','francicciomanuguerra@gmail.com','Non presente','Mobile','3289703900','DEP','133','Monti 2',NULL);
INSERT INTO Residence_DB VALUES ('Gianluca','Marano','gianluca.marano1@gmail.com','Non presente','Mobile','3661944844','LTM','140','Ponte 2',NULL);
INSERT INTO Residence_DB VALUES ('Simone','Marino','simone.marino97@outlook.it','Non presente','Mobile','3461275493','DEP','134','Parione 1',NULL);
INSERT INTO Residence_DB VALUES ('Vincenzo','Marino','vincenzomarino2098@gmail.com','Non presente','Mobile','3283796067','DEP','142','Pigna 2',NULL);
INSERT INTO Residence_DB VALUES ('Marco','Massone','mas.95@hotmail.it','Non presente','Mobile','3475864944','DEP','146','Borgo 1',NULL);
INSERT INTO Residence_DB VALUES ('Graziano','Miglionico','gramiglionico@gmail.com','Non presente','Mobile','3394288825','DEP','148','Ponte 2',NULL);
INSERT INTO Residence_DB VALUES ('Giuseppe','Milicia','milicia98@gmail.com','Non presente','Mobile','3421066962','LTM','141','Parione 3',NULL);
INSERT INTO Residence_DB VALUES ('Rosario','Mussari','Rosariomussari@gmail.com','Non presente','Mobile','3387163770','DEP','152','Ponte 1',NULL);
INSERT INTO Residence_DB VALUES ('Giuseppe','Notaristefano','peppenotaristefano99@gmail.com','Non presente','Mobile','3421522393','DEP','154','Parione 1',NULL);
INSERT INTO Residence_DB VALUES ('Luca','Oceana','lucad.oceana@gmail.com','Non presente','Mobile','3486192871','LTM','144','Monti 1',NULL);
INSERT INTO Residence_DB VALUES ('Emanuele','Paciolla','emanuele.paciolla15@gmail.com','Non presente','Mobile','3333166724','LTM','145','Monti 2',NULL);
INSERT INTO Residence_DB VALUES ('Davide','Pagliaro','dpagliaro97@gmail.com','Non presente','Mobile','3452126934','LTM','151','Pigna 2',NULL);
INSERT INTO Residence_DB VALUES ('Sergio Nunzio','Parisi','sergioparisi98@gmail.com','Non presente','Mobile','3335481057','DEP','155','Campo Marzio 1',NULL);
INSERT INTO Residence_DB VALUES ('Marco','Petralia','marcopetralia97@gmail.com','Non presente','Mobile','3899617483','LTM','107','Pigna 7',NULL);
INSERT INTO Residence_DB VALUES ('Giuseppe','Piano','giuseppe.piano98@gmail.com','Non presente','Mobile','3452645147','DEP','156','Colonna 1',NULL);
INSERT INTO Residence_DB VALUES ('Simone','Pizzini','smp98@hotmail.it','Non presente','Mobile','3318518958','DEP','164','Parione 1',NULL);
INSERT INTO Residence_DB VALUES ('Francesco','Pochì','france.pochi@gmail.com','Non presente','Mobile','3510525705/3892462704','DEP','165','Monti 1',NULL);
INSERT INTO Residence_DB VALUES ('Davide','Popolano','davide@popolano.it','Non presente','Mobile','3201562885','LTM','153','Campo Marzio 2',NULL);
INSERT INTO Residence_DB VALUES ('Francesco','Ricciardi','francesco.ricciardi993@gmail.com','Non presente','Mobile','3343384844','DEP','167','Ponte 1',NULL);
INSERT INTO Residence_DB VALUES ('Andrea','Rizzo','ioandrearizzo@gmail.com','Non presente','Mobile','3806340680','LTM','157','Campo Marzio 1',NULL);
INSERT INTO Residence_DB VALUES ('Antonio','Russo','russoantonio1997@gmail.com','Non presente','Mobile','3703458531','LTM','158','Ponte 3',NULL);
INSERT INTO Residence_DB VALUES ('Salvatore Pio','Russo','salvatorepiorusso@gmail.com','Non presente','Mobile','3271094422','DEP','172','Monti 1',NULL);
INSERT INTO Residence_DB VALUES ('Kerolos Naser Danial','Salib','kerolos.salib@gmail.com','Non presente','Mobile','3804645420','DEP','177','Campo Marzio 2',NULL);
INSERT INTO Residence_DB VALUES ('Pietro','Santochirico','pietro.santochirico@libero.it','Non presente','Mobile','3927294790','LTM','162','Campo Marzio 3',NULL);
INSERT INTO Residence_DB VALUES ('Simone','Scanzani','simonescanzani@outlook.com','Non presente','Mobile','3493207522','DEP','182','Monti 2',NULL);
INSERT INTO Residence_DB VALUES ('Andrea','Scarpiello','andrea.scarpiello.98@gmail.com','Non presente','Mobile','3885819301','DEP','184','Monti 2',NULL);
INSERT INTO Residence_DB VALUES ('Simone','Scifo','simone.scifo97@gmail.com','Non presente','Mobile','3391904321','LTM','163','Ponte 1',NULL);
INSERT INTO Residence_DB VALUES ('Gioele','Spinella','gioelespix@gmail.com','Non presente','Mobile','3396682798','DEP','185','Campo Marzio 1',NULL);
INSERT INTO Residence_DB VALUES ('Francesco','Stella','francesco.stella97@gmail.com','Non presente','Mobile','3295632453','LTM','166','Ponte 2',NULL);
INSERT INTO Residence_DB VALUES ('Giulio','Tandoi','tandoigiulio9@live.com','Non presente','Mobile','3465975836','DEP','186','Colonna 2',NULL);
INSERT INTO Residence_DB VALUES ('Valerio','Torrese','valerio.torrese@gmail.com','Non presente','Mobile','3273769772','LTM','174','Pigna 5',NULL);
INSERT INTO Residence_DB VALUES ('Federico','Tosto','tostofederico98@gmail.com','Non presente','Mobile','3314768385','DEP','187','Colonna 1',NULL);
INSERT INTO Residence_DB VALUES ('Andrea Mauro','Valenziano','valenzianoa@gmail.com','Non presente','Mobile','3485916588','LTM','175','Parione 1',NULL);
INSERT INTO Residence_DB VALUES ('Federico','Viceconti','viceconti.federico@gmail.com','Non presente','Mobile','3899549766','LTM','178','Campo Marzio 2',NULL);
INSERT INTO Residence_DB VALUES ('Donato','Virgilio','donato.virg@gmail.com','Non presente','Mobile','3403468139','LTM','143','Borgo 2',NULL);
INSERT INTO Residence_DB VALUES ('Salvatore','Zuardi','salvatorezuardi2697@gmail.com','Non presente','Mobile','3271656253','LTM','181','Pigna 2',NULL);
INSERT INTO Residence_DB VALUES ('Simone','Zuccala','simo4197@gmail.com','Non presente','Mobile','3272190767','LTM','193','Colonna 7',NULL);
INSERT INTO Residence_DB VALUES ('Agneti','Giuseppe','agneti.giuseppe@gmail.com','Non presente','Mobile','+39 366 456 4456','staff','102','Parione 5',NULL);
INSERT INTO Residence_DB VALUES ('Cavaglia','Pietro','pierocavaglia@hotmail.com','Non presente','Mobile','Non presente','staff','3','Non presente',NULL);
INSERT INTO Residence_DB VALUES ('Ferulano','Roberto','roberto.ferulano@gmail.com','Non presente','Mobile','+39 3477975557','staff','26','Monti 3',NULL);
INSERT INTO Residence_DB VALUES ('Mancino','Davide','davidemancino4@gmail.com','Non presente','Mobile','+39 3489233983','staff','109','Pigna 6',NULL);
INSERT INTO Residence_DB VALUES ('Messina','Marco','Non presente','Non presente','Mobile','Non presente','staff','159','Campo Marzio 6',NULL);
INSERT INTO Residence_DB VALUES ('Oceana','Gabriele','gabrieleoceana@gmail.com','Non presente','Mobile','+39 392 926 7135','staff','183','Ponte 4',NULL);
INSERT INTO Residence_DB VALUES ('Palmieri','Giuseppe','giuseppepalmieri96@gmail.com','Non presente','Mobile','+39 3481704613','staff','119','Colonna 4',NULL);
INSERT INTO Residence_DB VALUES ('Petraccone','Francesco','francesco.petraccone@gmail.com','Non presente','Mobile','+39 333 917 2944','staff','169','Campo Marzio 7',NULL);
INSERT INTO Residence_DB VALUES ('Fumagalli','Sergio','sergio_fumagalli@virgilio.it','Non presente','Mobile','Non presente','staff','/','Non presente',NULL);
INSERT INTO Residence_DB VALUES ('Guijarro','Alfonso','alfonso.guijarro@gmail.com','Non presente','Mobile','+39 3384988274','staff','/','Non presente',NULL);
INSERT INTO Residence_DB VALUES ('Cavalleri','Giampietro','giampicavalleri@gmail.com','Non presente','Mobile','Non presente','staff','150','Non presente',NULL);
INSERT INTO Residence_DB VALUES ('Pontari','Domenico','D.Pontari@elis.org','Non presente','Mobile','+39 346 237 3509','staff','41','Direzione',NULL);
INSERT INTO Residence_DB VALUES ('Re','Paolo','paolore1@gmail.com','Non presente','Mobile','+39 3394026631','staff','10','Non presente',NULL);
INSERT INTO Residence_DB VALUES ('Politano','Vincenzo','vincenzopolitano94@gmail.com','Non presente','Mobile','393335324390','staff','77','Monti 7',NULL);
INSERT INTO Residence_DB VALUES ('Tallarita','Gianbattista','Non presente','Non presente','Mobile','Non presente','staff','179','Parione 4 ',NULL);
INSERT INTO Residence_DB VALUES ('Gigliotti','Carlo Pio','carlo.gigliotticg@gmail.com','Non presente','Mobile','+39 392 726 9647','staff','149','Borgo 3',NULL);
